package cops

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/dgageot/rubocop-go/coptest"
)

func TestStdlibUUID(t *testing.T) {
	requireGo127(t)
	t.Parallel()
	offenses := coptest.RunProgram(t, NewLintStdlibUUID(), coptest.ProgramFiles{
		"go.mod":        "module example.test\n\ngo 1.27\nrequire github.com/google/uuid v0.0.0\nreplace github.com/google/uuid => ./google\n",
		"google/go.mod": "module github.com/google/uuid\n\ngo 1.27\n",
		"google/uuid.go": `package uuid
 type UUID [16]byte
 func (UUID) String() string { return "id" }
 func New() UUID { return UUID{} }
 func NewString() string { return "id" }
 func MustParse(string) UUID { return UUID{} }
 func Parse(string) (UUID,error) { return UUID{},nil }
 func NewSHA1(UUID, []byte) UUID { return UUID{} }
`,
		"uuid.go": `package p
import id "github.com/google/uuid"
func f(s string) {
 _ = id.NewString()
 _ = id.MustParse("6f0c2a1e-8d4b-4c7f-9a3e-2b5d7e9f1c03")
 _ = id.New().String()
 _ = id.MustParse("6f0c2a1e-8d4b-4c7f-9a3e-2b5d7e9f1c03").String()
 _ = id.New()
 _ = id.NewSHA1(id.UUID{}, []byte(s)).String()
 _,_ = id.Parse(s)
 _ = id.MustParse(s)
 _ = id.MustParse("{6f0c2a1e-8d4b-4c7f-9a3e-2b5d7e9f1c03}")
 _ = id.MustParse("invalid")
}
`,
		"stdlib.go": `package p
import "uuid"
func std() string { return uuid.NewV4().String() }
`,
		"other/other.go": `package uuid
func NewString() string { return "id" }; func f() { _ = NewString() }
`,
		"pkg/config/v1/frozen.go": `package v1
import "github.com/google/uuid"
var frozen = uuid.NewString()
`,
		"generated.go": `// Code generated by fixture. DO NOT EDIT.
package p
import "github.com/google/uuid"
var generated = uuid.NewString()
`,
	})
	require.Len(t, offenses, 4)
	for _, offense := range offenses {
		assert.Equal(t, "Lint/StdlibUUID", offense.CopName)
	}
}

func TestCanonicalUUID(t *testing.T) {
	t.Parallel()
	for _, s := range []string{"6f0c2a1e-8d4b-4c7f-9a3e-2b5d7e9f1c03", "6F0C2A1E-8D4B-4C7F-9A3E-2B5D7E9F1C03"} {
		assert.True(t, canonicalUUID(s))
	}
	for _, s := range []string{"", "6f0c2a1e_8d4b-4c7f-9a3e-2b5d7e9f1c03", "gf0c2a1e-8d4b-4c7f-9a3e-2b5d7e9f1c03", "6f0c2a1e8d4b4c7f9a3e2b5d7e9f1c03"} {
		assert.False(t, canonicalUUID(s))
	}
}

func TestStdlibUUIDCustomRandomness(t *testing.T) {
	requireGo127(t)
	t.Parallel()
	for _, name := range []string{"SetRand", "EnableRandPool", "DisableRandPool"} {
		for _, path := range []string{"random.go", "random_test.go"} {
			t.Run(name+"/"+path, func(t *testing.T) {
				t.Parallel()
				files := coptest.ProgramFiles{
					"go.mod":         "module example.test\n\ngo 1.27\nrequire github.com/google/uuid v0.0.0\nreplace github.com/google/uuid => ./google\n",
					"google/go.mod":  "module github.com/google/uuid\n\ngo 1.27\n",
					"google/uuid.go": "package uuid\nfunc NewString() string { return \"id\" }\nfunc " + name + "() {}\n",
					"uuid.go":        "package p\nimport \"github.com/google/uuid\"\nfunc ID() string { return uuid.NewString() }\n",
					path:             "package p\nimport alias \"github.com/google/uuid\"\nvar configureRandomness = alias." + name + "\n",
				}
				assert.Empty(t, coptest.RunProgram(t, NewLintStdlibUUID(), files))
			})
		}
	}
}
