package cops

import (
	"errors"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/dgageot/rubocop-go/cop"
	"github.com/dgageot/rubocop-go/coptest"
)

const errorsAsTypeFixture = `package p
import "errors"
type E struct{}
func (*E) Error() string { return "e" }
func f(err *E) { var e *E; if errors.As(err, &e) { println(e) } }
`

func TestErrorsAsType(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, body string
		want       int
	}{
		{"fresh", `var e *E; if errors.As(err, &e) { println(e) }`, 1},
		{"interface error", `var e error; if errors.As(err, &e) { println(e) }`, 1},
		{"parenthesized", `var e *E; if (errors.As((err), (&(e)))) { println(e) }`, 1},
		{"success capture", `var e *E; if errors.As(err, &e) { func() { println(e) }() }`, 1},
		{"failed path independent", `var e *E; if errors.As(err, &e) { println(e) } else { println(err) }`, 1},
		{"nested shadow", `var e *E; if errors.As(err, &e) { println(e); { e := 1; println(&e) } }`, 1},
		{"switch case", `switch { default: var e *E; if errors.As(err, &e) { println(e) } }`, 1},
		{"select case", `select { default: var e *E; if errors.As(err, &e) { println(e) } }`, 1},
		{"failed path", `var e *E; if errors.As(err, &e) { println(e) } else { println(e) }`, 0},
		{"later read", `var e *E; if errors.As(err, &e) { println(e) }; println(e)`, 0},
		{"later write", `var e *E; if errors.As(err, &e) { println(e) }; e = nil`, 0},
		{"later capture", `var e *E; if errors.As(err, &e) { println(e) }; func() { println(e) }()`, 0},
		{"failed path capture", `var e *E; if errors.As(err, &e) { println(e) } else { func() { println(e) }() }`, 0},
		{"source capture", `var e *E; if errors.As(func() error { e = err; return err }(), &e) { println(e) }`, 0},
		{"source read", `var e *E; if errors.As(e, &e) { println(e) }`, 0},
		{"initialized", `e := new(E); if errors.As(err, &e) { println(e) }`, 0},
		{"explicit zero initializer", `var e *E = nil; if errors.As(err, &e) { println(e) }`, 0},
		{"multiple names", `var e, other *E; if errors.As(err, &e) { println(e, other) }`, 0},
		{"address escapes", `var e *E; if errors.As(err, &e) { println(&e) }`, 0},
		{"capture address escapes", `var e *E; if errors.As(err, &e) { func() { println(&e) }() }`, 0},
		{"nonerror interface", `var e interface{ String() string }; if errors.As(err, &e) { println(e) }`, 0},
		{"any interface", `var e any; if errors.As(err, &e) { println(e) }`, 0},
		{"nonerror value", `var e E; if errors.As(err, &e) { println(e) }`, 0},
		{"compound", `var e *E; if err != nil && errors.As(err, &e) { println(e) }`, 0},
		{"if initializer", `var e *E; if ok := true; errors.As(err, &e) { println(e, ok) }`, 0},
		{"intervening", `var e *E; println(err); if errors.As(err, &e) { println(e) }`, 0},
		{"shadowed", `_ = errors.As; var e *E; errors := struct{ As func(error, any) bool }{}; if errors.As(err, &e) { println(e) }`, 0},
	} {
		t.Run(tc.name, func(t *testing.T) {
			src := strings.Replace(errorsAsTypeFixture, `var e *E; if errors.As(err, &e) { println(e) }`, tc.body, 1)
			offenses := runExtractedTypedCop(t, newErrorsAsTypeFile(), src)
			require.Len(t, offenses, tc.want)
			if tc.want != 0 {
				assert.Contains(t, offenses[0].Message, "errors.AsType")
				assert.Greater(t, offenses[0].End.Offset, offenses[0].Pos.Offset)
			}
		})
	}
	assert.Len(t, runExtractedTypedCop(t, newErrorsAsTypeFile(), strings.ReplaceAll(strings.ReplaceAll(errorsAsTypeFixture, `import "errors"`, `import chain "errors"`), "errors.As", "chain.As")), 1)
	assert.Empty(t, runExtractedTypedCop(t, newErrorsAsTypeFile(), "// Code generated by test; DO NOT EDIT.\n"+errorsAsTypeFixture))
	assert.Empty(t, runExtractedTypedCop(t, newErrorsAsTypeFile(cop.WithMinStdlibVersion("go1.27")), errorsAsTypeFixture))
	assert.Equal(t, "go1.26", newErrorsAsTypeFile(cop.WithMinStdlibVersion("go1.20")).MinStdlibVersion)
	assert.Empty(t, coptest.Run(t, newErrorsAsTypeFile(), errorsAsTypeFixture))
}

func TestErrorsAsTypeSourceRestrictions(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, source, target, declarations string
		want                               int
	}{
		{"dynamic error", "error", "*E", "", 0},
		{"dynamic direct match", "error", "error", "", 1},
		{"concrete leaf", "*Leaf", "*E", `type Leaf struct{}; func (*Leaf) Error() string { return "leaf" }`, 1},
		{"custom As", "*Custom", "*E", `type Custom struct{ target **E }; func (*Custom) Error() string { return "custom" }; func (c *Custom) As(target any) bool { c.target = target.(**E); *c.target = new(E); return true }`, 0},
		{"custom As direct match", "*Custom", "*Custom", `type Custom struct{}; func (*Custom) Error() string { return "custom" }; func (*Custom) As(any) bool { panic("unreachable") }`, 1},
		{"single unwrap", "*Wrapper", "*E", `type Wrapper struct{ error }; func (w *Wrapper) Unwrap() error { return w.error }`, 0},
		{"multi unwrap", "*Wrapper", "*E", `type Wrapper struct{}; func (*Wrapper) Error() string { return "wrapper" }; func (*Wrapper) Unwrap() []error { return nil }`, 0},
		{"promoted As", "*Wrapper", "*E", `type Custom struct{}; func (*Custom) Error() string { return "custom" }; func (*Custom) As(any) bool { return true }; type Wrapper struct{ *Custom }`, 0},
		{"named interface target", "error", "Error", `type Error interface{ Error() string }`, 1},
		{"alias target", "*E", "Alias", `type Alias = *E`, 1},
		{"assignable anonymous value", "struct{ error }", "Named", `type Named struct{ error }`, 0},
		{"generic same underlying type", "T", "Named", `type Named struct{ error }`, 0},
		{"concrete named source generic target", "Named", "T", `type Named struct{ error }`, 0},
		{"generic target same underlying type", "struct{ error }", "T", "", 0},
		{"value target", "Value", "Value", `type Value struct{}; func (Value) Error() string { return "value" }`, 1},
		{"pointer to interface target", "error", "*error", "", 0},
		{"generic unknown source", "T", "*E", "", 0},
		{"generic direct match", "T", "T", "", 1},
	} {
		t.Run(tc.name, func(t *testing.T) {
			src := strings.Replace(errorsAsTypeFixture, "err *E", "err "+tc.source, 1)
			src = strings.Replace(src, "var e *E", "var e "+tc.target, 1)
			if tc.source == "T" || tc.target == "T" {
				constraint := "error"
				if tc.target == "Named" || tc.source == "Named" || tc.source == "struct{ error }" {
					constraint = "interface{ error; ~struct{ error } }"
				}
				src = strings.Replace(src, "func f(", "func f[T "+constraint+"](", 1)
			}
			src += "\n" + tc.declarations
			require.Len(t, runExtractedTypedCop(t, newErrorsAsTypeFile(), src), tc.want)
		})
	}
}

type errorsAsTypeRetainerError struct {
	target **errorsAsTypeRetainerError
}

func (*errorsAsTypeRetainerError) Error() string { return "retainer" }

func (e *errorsAsTypeRetainerError) As(target any) bool {
	e.target = target.(**errorsAsTypeRetainerError)
	*e.target = e
	return true
}

// Hide the retainer's concrete type to force the custom As path.
type errorsAsTypeWrapperError struct{ *errorsAsTypeRetainerError }

func TestErrorsAsTypeCustomAsTargetAlias(t *testing.T) {
	t.Parallel()
	original := &errorsAsTypeRetainerError{}
	var target *errorsAsTypeRetainerError
	require.ErrorAs(t, errorsAsTypeWrapperError{original}, &target)
	*original.target = nil
	assert.Nil(t, target)

	modernized := &errorsAsTypeRetainerError{}
	result, ok := errors.AsType[*errorsAsTypeRetainerError](errorsAsTypeWrapperError{modernized})
	require.True(t, ok)
	*modernized.target = nil
	assert.Same(t, modernized, result, "AsType returns a copy, not the target retained by custom As")
}

func TestErrorsAsTypeAssignableDifferentDynamicType(t *testing.T) {
	t.Parallel()
	type named struct{ error }
	source := struct{ error }{errors.New("source")}
	var original named
	require.ErrorAs(t, source, &original)
	assert.Same(t, source.error, original.error)

	_, ok := errors.AsType[named](source)
	assert.False(t, ok, "type assertions require identical non-interface dynamic types")
}

type errorsAsTypeNamedError struct{ error }

func errorsAsTypeGenericTarget[T interface {
	error
	~struct{ error }
}](t *testing.T, source errorsAsTypeNamedError) T {
	t.Helper()
	var target T
	require.ErrorAs(t, source, &target)
	return target
}

func TestErrorsAsTypeGenericTargetAssignability(t *testing.T) {
	t.Parallel()
	source := errorsAsTypeNamedError{errors.New("source")}
	original := errorsAsTypeGenericTarget[struct{ error }](t, source)
	assert.Same(t, source.error, original.error)

	_, ok := errors.AsType[struct{ error }](source)
	assert.False(t, ok, "a generic target can be assignable without matching the dynamic type")
}

func TestErrorsAsTypeProgram(t *testing.T) {
	t.Parallel()
	offenses := coptest.RunProgram(t, NewLintErrorsAsType(cop.WithScope(cop.Not(cop.UnderDir("legacy")))), coptest.ProgramFiles{
		"go.mod":                  "module example.test\n\ngo 1.26\n",
		"sample.go":               errorsAsTypeFixture,
		"internal/sample_test.go": errorsAsTypeFixture,
		"external/sample_test.go": strings.Replace(errorsAsTypeFixture, "package p", "package p_test", 1),
		"legacy/sample.go":        errorsAsTypeFixture,
		"generated/sample.go":     "// Code generated by test; DO NOT EDIT.\n" + errorsAsTypeFixture,
	})
	require.Len(t, offenses, 3)
	for _, offense := range offenses {
		assert.Equal(t, "Lint/ErrorsAsType", offense.CopName)
	}
}
