package cops

import (
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/dgageot/rubocop-go/cop"
)

const mapsCopyFixture = `package p
func f(dst, src map[string]int) {
 for k, v := range src { dst[k] = v }
}`

func TestMapsCopy(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, src string
		want      int
	}{
		{"plain", `func f(dst, src map[string]int) { for k, v := range src { dst[k] = v } }`, 1},
		{"named maps", `type M map[string]int; func f(dst, src M) { for k, v := range src { dst[k] = v } }`, 1},
		{"aliases", `type M = map[string]int; func f(dst, src M) { for k, v := range src { dst[k] = v } }`, 1},
		{"distinct named maps", `type M map[string]int; type N map[string]int; func f(dst M, src N) { for k, v := range src { dst[k] = v } }`, 1},
		{"local declarations", `func f() { src := map[int]int{1: 2}; dst := map[int]int{}; for k, v := range src { dst[k] = v } }`, 1},
		{"parentheses", `func f(dst, src map[int]int) { for k, v := range (src) { (dst)[(k)] = (v) } }`, 1},
		{"self copy", `func f(src map[int]int) { for k, v := range src { src[k] = v } }`, 1},
		{"NaN keys copy uses same loop", `func f(dst, src map[float64]int) { for k, v := range src { dst[k] = v } }`, 1},
		{"shadowed outer names", `func f(dst, src map[int]int, k, v int) { for k, v := range src { dst[k] = v }; _, _ = k, v }`, 1},
		{"assigned range variables", `func f(dst, src map[int]int) { var k, v int; for k, v = range src { dst[k] = v }; _, _ = k, v }`, 0},
		{"blank value", `func f(dst, src map[int]int) { for k, _ := range src { dst[k] = src[k] } }`, 0},
		{"key only", `func f(dst, src map[int]int) { for k := range src { dst[k] = src[k] } }`, 0},
		{"extra work", `func f(dst, src map[int]int) { for k, v := range src { dst[k] = v; println(k) } }`, 0},
		{"callback", `func f(dst, src map[int]int, transform func(int) int) { for k, v := range src { dst[k] = transform(v) } }`, 0},
		{"filter", `func f(dst, src map[int]int) { for k, v := range src { if k > 0 { dst[k] = v } } }`, 0},
		{"different value", `func f(dst, src map[int]int, v int) { for k := range src { dst[k] = v } }`, 0},
		{"different key", `func f(dst, src map[int]int, key int) { for _, v := range src { dst[key] = v } }`, 0},
		{"global source", `var src map[int]int; func f(dst map[int]int) { for k, v := range src { dst[k] = v } }`, 0},
		{"global destination", `var dst map[int]int; func f(src map[int]int) { for k, v := range src { dst[k] = v } }`, 0},
		{"field destination", `type S struct { dst map[int]int }; func f(s S, src map[int]int) { for k, v := range src { s.dst[k] = v } }`, 0},
		{"field source", `type S struct { src map[int]int }; func f(s S, dst map[int]int) { for k, v := range s.src { dst[k] = v } }`, 0},
		{"effectful source", `func f(dst map[int]int, get func() map[int]int) { for k, v := range get() { dst[k] = v } }`, 0},
		{"effectful destination", `func f(src map[int]int, get func() map[int]int) { for k, v := range src { get()[k] = v } }`, 0},
		{"assignable but different value types", `func f(dst map[int]any, src map[int]int) { for k, v := range src { dst[k] = v } }`, 0},
		{"slice range", `func f(dst map[int]int, src []int) { for k, v := range src { dst[k] = v } }`, 0},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			offenses := runExtractedTypedCop(t, newMapsCopyFile(), "package p\n"+tc.src)
			require.Len(t, offenses, tc.want)
			for _, offense := range offenses {
				assert.Equal(t, "Lint/MapsCopy", offense.CopName)
				assert.Equal(t, cop.Convention, offense.Severity)
				assert.Contains(t, offense.Message, "maps.Copy(dst, src)")
				assert.Equal(t, 2, offense.Pos.Line)
				assert.Greater(t, offense.End.Offset, offense.Pos.Offset)
			}
		})
	}
}

func TestMapsCopyConfiguration(t *testing.T) {
	t.Parallel()
	c := newMapsCopyFile()
	require.NotSame(t, c, newMapsCopyFile())
	assert.True(t, c.Types)
	assert.True(t, c.NeedsTypes())
	assert.Nil(t, c.Scope)
	assert.Equal(t, "go1.21", c.MinStdlibVersion)
	assert.Equal(t, "go1.21", newMapsCopyFile(cop.WithMinStdlibVersion("go1.20")).MinStdlibVersion)
	assert.Equal(t, "go1.30", newMapsCopyFile(cop.WithMinStdlibVersion("go1.30")).MinStdlibVersion)
	assert.Empty(t, runExtractedTypedCop(t, newMapsCopyFile(cop.WithMinStdlibVersion("go1.30")), mapsCopyFixture))
	assert.Empty(t, runExtractedTypedCop(t, c, "// Code generated by fixture; DO NOT EDIT.\n"+mapsCopyFixture))
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "internal/sample_test.go", mapsCopyFixture, parser.ParseComments)
	require.NoError(t, err)
	info := &types.Info{
		Types: make(map[ast.Expr]types.TypeAndValue), Defs: make(map[*ast.Ident]types.Object),
		Uses: make(map[*ast.Ident]types.Object), FileVersions: make(map[*ast.File]string),
	}
	cfg := types.Config{Importer: importer.Default()}
	_, err = cfg.Check("fixture", fset, []*ast.File{file}, info)
	require.NoError(t, err)
	for _, target := range []string{"", "go1.20", "go1.21", "go1.26"} {
		info.FileVersions[file] = target
		pass := &cop.Pass{Cop: c, FileSet: fset, File: file, Info: info}
		c.Check(pass)
		if target == "" || target == "go1.20" {
			assert.Empty(t, pass.Offenses(), target)
		} else {
			assert.Len(t, pass.Offenses(), 1, target)
		}
	}
	pass := &cop.Pass{Cop: c, FileSet: fset, File: file}
	c.Run(pass)
	assert.Empty(t, pass.Offenses(), "missing types")
	assert.True(t, newMapsCopyFile(cop.WithScope(cop.UnderDir("internal"))).InScope(pass))
	assert.False(t, newMapsCopyFile(cop.WithScope(cop.UnderDir("other"))).InScope(pass))
}
