package cops

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/dgageot/rubocop-go/coptest"
)

func TestPointerHelper(t *testing.T) {
	t.Parallel()
	offenses := coptest.RunProgram(t, NewLintPointerHelper(), coptest.ProgramFiles{
		"go.mod":     "module example.test\n\ngo 1.26\nrequire github.com/aws/aws-sdk-go-v2 v0.0.0\nreplace github.com/aws/aws-sdk-go-v2 => ./aws\n",
		"aws/go.mod": "module github.com/aws/aws-sdk-go-v2\n\ngo 1.26\n",
		"aws/aws/pointer.go": `package aws
func String(v string) *string { return &v }
func Int32(v int32) *int32 { return &v }
func StringSlice(v []string) []*string { return nil }
func ToString(v *string) string { return *v }
`,
		"pointer.go": `package p
import sdk "github.com/aws/aws-sdk-go-v2/aws"
func f(s string) { _ = sdk.String(s); _ = sdk.Int32(1); _ = sdk.Int32(int32(len(s))) }
func allowed(s string) { _ = sdk.StringSlice([]string{s}); _ = sdk.ToString(&s) }
func shadowed(new int) { _ = sdk.String("x") }
func shadowedType(int32 int) { _ = sdk.Int32(1) }
`,
		"generated.go": `// Code generated by fixture. DO NOT EDIT.
package p
import "github.com/aws/aws-sdk-go-v2/aws"
var generated = aws.String("x")
`,
		"pkg/config/v1/frozen.go": `package v1
import "github.com/aws/aws-sdk-go-v2/aws"
var frozen = aws.String("x")
`,
		"other/other.go": `package aws
func String(s string) *string { return &s }
func f() { _ = String("x") }
`,
	})
	require.Len(t, offenses, 4)
	for _, offense := range offenses {
		assert.Equal(t, "Lint/PointerHelper", offense.CopName)
		assert.Contains(t, offense.Message, "conversion")
	}
}
