package cops

import (
	"go/ast"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/dgageot/rubocop-go/cop"
	"github.com/dgageot/rubocop-go/coptest"
)

const httpTestRequestWithContextFixture = `package p
import ("context"; "net/http"; "net/http/httptest")
func f(ctx context.Context) *http.Request {
 return httptest.NewRequest("GET", "/", nil).WithContext(ctx)
}`

func TestHTTPTestRequestWithContext(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, expression string
		want             int
	}{
		{"local context", `httptest.NewRequest("GET", "/", nil).WithContext(ctx)`, 1},
		{"parentheses", `(httptest.NewRequest(("GET"), ("/"), (nil))).WithContext((ctx))`, 1},
		{"empty method", `httptest.NewRequest("", "/", nil).WithContext(ctx)`, 1},
		{"https", `httptest.NewRequest("GET", "https://example.test/", nil).WithContext(ctx)`, 1},
		{"invalid method", `httptest.NewRequest("BAD METHOD", "/", nil).WithContext(ctx)`, 1},
		{"invalid target", `httptest.NewRequest("GET", "%", nil).WithContext(ctx)`, 1},
		{"background", `httptest.NewRequest("GET", "/", nil).WithContext(context.Background())`, 1},
		{"todo", `httptest.NewRequest("GET", "/", nil).WithContext(context.TODO())`, 1},
		{"already contextual", `httptest.NewRequestWithContext(ctx, "GET", "/", nil)`, 0},
		{"no context", `httptest.NewRequest("GET", "/", nil)`, 0},
		{"nil context", `httptest.NewRequest("GET", "/", nil).WithContext(nil)`, 0},
		{"body", `httptest.NewRequest("GET", "/", strings.NewReader("x")).WithContext(ctx)`, 0},
		{"effectful context", `httptest.NewRequest("GET", "/", nil).WithContext(func() context.Context { println("side effect"); return ctx }())`, 0},
		{"field context", `httptest.NewRequest("GET", "/", nil).WithContext((&struct{ c context.Context }{ctx}).c)`, 0},
		{"nonconstant target", `httptest.NewRequest("GET", strings.TrimSpace(" / "), nil).WithContext(ctx)`, 0},
		{"Clone", `httptest.NewRequest("GET", "/", nil).Clone(ctx)`, 0},
	} {
		t.Run(tc.name, func(t *testing.T) {
			src := strings.Replace(httpTestRequestWithContextFixture, `httptest.NewRequest("GET", "/", nil).WithContext(ctx)`, tc.expression, 1)
			if strings.Contains(tc.expression, "strings.") {
				src = strings.Replace(src, `"context";`, `"strings"; "context";`, 1)
			}
			offenses := runExtractedTypedCop(t, newHTTPTestRequestWithContextFile(), src)
			require.Len(t, offenses, tc.want)
			if tc.want != 0 {
				assert.Contains(t, offenses[0].Message, "httptest.NewRequestWithContext")
				assert.Greater(t, offenses[0].End.Offset, offenses[0].Pos.Offset)
			}
		})
	}
	src := strings.Replace(httpTestRequestWithContextFixture, `"net/http/httptest"`, `testhttp "net/http/httptest"`, 1)
	assert.Len(t, runExtractedTypedCop(t, newHTTPTestRequestWithContextFile(), strings.ReplaceAll(src, "httptest.", "testhttp.")), 1)
	src = strings.Replace(httpTestRequestWithContextFixture, `return httptest`, `_ = httptest.NewRequest; httptest := struct{ NewRequest func(string, string, any) *http.Request }{}; return httptest`, 1)
	assert.Empty(t, runExtractedTypedCop(t, newHTTPTestRequestWithContextFile(), src))
	src = strings.Replace(httpTestRequestWithContextFixture, "func f(ctx context.Context)", "var ctx context.Context\nfunc f()", 1)
	assert.Empty(t, runExtractedTypedCop(t, newHTTPTestRequestWithContextFile(), src))
	assert.Empty(t, runExtractedTypedCop(t, newHTTPTestRequestWithContextFile(), "// Code generated by test; DO NOT EDIT.\n"+httpTestRequestWithContextFixture))
	assert.Empty(t, runExtractedTypedCop(t, newHTTPTestRequestWithContextFile(cop.WithMinStdlibVersion("go1.27")), httpTestRequestWithContextFixture))
	assert.Equal(t, "go1.23", newHTTPTestRequestWithContextFile(cop.WithMinStdlibVersion("go1.20")).MinStdlibVersion)
	assert.Empty(t, coptest.Run(t, newHTTPTestRequestWithContextFile(), httpTestRequestWithContextFixture))
}

func TestHTTPTestRequestWithContextProgram(t *testing.T) {
	t.Parallel()
	offenses := coptest.RunProgram(t, NewLintHTTPTestRequestWithContext(cop.WithScope(cop.Not(cop.UnderDir("legacy")))), coptest.ProgramFiles{
		"go.mod":                  "module example.test\n\ngo 1.26\n",
		"sample.go":               httpTestRequestWithContextFixture,
		"sample_test.go":          strings.Replace(httpTestRequestWithContextFixture, "func f(", "func internalTest(", 1),
		"external_test.go":        strings.Replace(httpTestRequestWithContextFixture, "package p", "package p_test", 1),
		"internal/sample_test.go": httpTestRequestWithContextFixture,
		"external/sample_test.go": strings.Replace(httpTestRequestWithContextFixture, "package p", "package p_test", 1),
		"legacy/sample.go":        httpTestRequestWithContextFixture,
		"generated/sample.go":     "// Code generated by test; DO NOT EDIT.\n" + httpTestRequestWithContextFixture,
	})
	require.Len(t, offenses, 5)
	for _, offense := range offenses {
		assert.Equal(t, "Lint/HTTPTestRequestWithContext", offense.CopName)
	}
}

func TestHTTPTestRequestWithContextTypes(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, declarations, signature, body string
		want                                int
	}{
		{"named string constants", `type Text string; const method Text = "GET"; const target Text = "/"`, `func f(ctx context.Context)`, `return httptest.NewRequest(string(method), string(target), nil).WithContext(ctx)`, 1},
		{"context alias", `type C = context.Context`, `func f(ctx C)`, `return httptest.NewRequest("GET", "/", nil).WithContext(ctx)`, 1},
		{"named context interface", `type C interface { context.Context }`, `func f(ctx C)`, `return httptest.NewRequest("GET", "/", nil).WithContext(ctx)`, 1},
		{"generic context", ``, `func f[C context.Context](ctx C)`, `return httptest.NewRequest("GET", "/", nil).WithContext(ctx)`, 1},
		{"concrete typed nil", `type C struct { context.Context }`, `func f(ctx *C)`, `return httptest.NewRequest("GET", "/", nil).WithContext(ctx)`, 1},
		{"local nil interface", ``, `func f(ctx context.Context)`, `ctx = nil; return httptest.NewRequest("GET", "/", nil).WithContext(ctx)`, 1},
		{"captured context", ``, `func f(ctx context.Context)`, `return func() *http.Request { return httptest.NewRequest("GET", "/", nil).WithContext(ctx) }()`, 1},
		{"typed nil expression", ``, `func f(ctx context.Context)`, `return httptest.NewRequest("GET", "/", nil).WithContext(context.Context(nil))`, 0},
		{"typed nil body", ``, `func f(ctx context.Context)`, `return httptest.NewRequest("GET", "/", (*strings.Reader)(nil)).WithContext(ctx)`, 0},
		{"nonconstant method", ``, `func f(ctx context.Context)`, `method := "GET"; return httptest.NewRequest(method, "/", nil).WithContext(ctx)`, 0},
		{"request temporary", ``, `func f(ctx context.Context)`, `req := httptest.NewRequest("GET", "/", nil); return req.WithContext(ctx)`, 0},
	} {
		t.Run(tc.name, func(t *testing.T) {
			src := `package p; import ("context"; "net/http"; "net/http/httptest"); ` + tc.declarations + "\n" + tc.signature + ` *http.Request { ` + tc.body + ` }`
			if strings.Contains(tc.body, "strings.") {
				src = strings.Replace(src, `"context";`, `"strings"; "context";`, 1)
			}
			assert.Len(t, runExtractedTypedCop(t, newHTTPTestRequestWithContextFile(), src), tc.want)
			if tc.want != 0 {
				modernized := strings.ReplaceAll(src, "httptest.NewRequest(", "httptest.NewRequestWithContext(ctx, ")
				modernized = strings.ReplaceAll(modernized, ".WithContext(ctx)", "")
				assert.Empty(t, runExtractedTypedCop(t, newHTTPTestRequestWithContextFile(), modernized))
			}
		})
	}
}

func TestHTTPTestRequestWithContextIncompleteTypes(t *testing.T) {
	t.Parallel()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "sample.go", httpTestRequestWithContextFixture, parser.ParseComments)
	require.NoError(t, err)
	c := newHTTPTestRequestWithContextFile()
	for _, info := range []*types.Info{nil, {}} {
		pass := &cop.Pass{Cop: c, FileSet: fset, File: file, Info: info}
		assert.NotPanics(t, func() { c.Run(pass) })
		assert.Empty(t, pass.Offenses())
	}
	info := &types.Info{
		Types: make(map[ast.Expr]types.TypeAndValue), Defs: make(map[*ast.Ident]types.Object),
		Uses: make(map[*ast.Ident]types.Object), Selections: make(map[*ast.SelectorExpr]*types.Selection),
	}
	_, err = (&types.Config{Importer: importer.Default()}).Check("fixture", fset, []*ast.File{file}, info)
	require.NoError(t, err)
	for _, partial := range []*types.Info{
		{Types: info.Types, Selections: info.Selections},
		{Uses: info.Uses, Selections: info.Selections},
		{Types: info.Types, Uses: info.Uses},
	} {
		pass := &cop.Pass{Cop: c, FileSet: fset, File: file, Info: partial}
		assert.NotPanics(t, func() { c.Run(pass) })
		assert.Empty(t, pass.Offenses())
	}
}

func TestHTTPTestRequestWithContextPreservesRequests(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct{ method, target string }{
		{"GET", "/"},
		{"", "/"},
		{"POST", "http://example.test/path?q=value"},
		{"GET", "https://example.test/"},
		{"OPTIONS", "*"},
	} {
		t.Run(tc.method+" "+tc.target, func(t *testing.T) {
			ctx := t.Context()
			original := httptest.NewRequest(tc.method, tc.target, nil).WithContext(ctx) //nolint:gocritic // Exercise the exact nil-body pattern matched by the cop.
			modernized := httptest.NewRequestWithContext(ctx, tc.method, tc.target, nil)
			assert.Equal(t, original, modernized)
			assert.Equal(t, ctx, modernized.Context())
		})
	}
}

func TestHTTPTestRequestWithContextPreservesPanics(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, method, target string
		nilContext           bool
		panicPrefix          string
	}{
		{"nil context", "GET", "/", true, "nil context"},
		{"invalid method before nil context", "BAD METHOD", "/", true, "invalid NewRequest arguments;"},
		{"invalid target before nil context", "GET", "%", true, "invalid NewRequest arguments;"},
		{"invalid method", "BAD METHOD", "/", false, "invalid NewRequest arguments;"},
		{"invalid target", "GET", "%", false, "invalid NewRequest arguments;"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			ctx := t.Context()
			if tc.nilContext {
				ctx = nil
			}
			var originalPanic string
			for i, newRequest := range []func() *http.Request{
				func() *http.Request {
					return httptest.NewRequest(tc.method, tc.target, nil).WithContext(ctx) //nolint:gocritic // Exercise the cop's nil-body pattern.
				},
				func() *http.Request { return httptest.NewRequestWithContext(ctx, tc.method, tc.target, nil) },
			} {
				func() {
					defer func() {
						value := recover()
						require.NotNil(t, value)
						message, ok := value.(string)
						require.True(t, ok)
						assert.True(t, strings.HasPrefix(message, tc.panicPrefix), message)
						if i == 0 {
							originalPanic = message
						} else {
							assert.Equal(t, originalPanic, message)
						}
					}()
					newRequest()
				}()
			}
		})
	}
}
