package cops

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/dgageot/rubocop-go/cop"
	"github.com/dgageot/rubocop-go/coptest"
)

func TestMapsCloneProgram(t *testing.T) {
	t.Parallel()
	c := NewLintMapsClone(cop.WithScope(cop.Not(cop.UnderDir("legacy"))))
	require.NotSame(t, c, NewLintMapsClone())
	offenses := coptest.RunProgram(t, c, coptest.ProgramFiles{
		"go.mod":                  "module example.test\n\ngo 1.26\n",
		"sample.go":               mapsCloneFixture,
		"internal/sample_test.go": mapsCloneFixture,
		"external/sample_test.go": strings.Replace(mapsCloneFixture, "package p", "package p_test", 1),
		"legacy/sample.go":        mapsCloneFixture,
		"generated/sample.go":     "// Code generated by test; DO NOT EDIT.\n" + mapsCloneFixture,
	})
	require.Len(t, offenses, 3)
	for _, offense := range offenses {
		assert.Equal(t, "Lint/MapsClone", offense.CopName)
		assert.Greater(t, offense.End.Offset, offense.Pos.Offset)
	}
}
