package cops

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/dgageot/rubocop-go/config"
	"github.com/dgageot/rubocop-go/cop"
	"github.com/dgageot/rubocop-go/coptest"
	"github.com/dgageot/rubocop-go/prog"
	"github.com/dgageot/rubocop-go/runner"
)

func TestSlicesClone(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		name, src string
		want      int
	}{
		{"nil append", `func f(s []int) []int { return append([]int(nil), s...) }`, 1},
		{"empty append", `func f(s []int) []int { return append([]int{}, s...) }`, 1},
		{"make append", `func f(s []int) []int { return append(make([]int, 0), s...) }`, 1},
		{"named slice", `type S []int; func f(s S) S { return append(S(nil), s...) }`, 1},
		{"parentheses", `func f(s []int) []int { return (append)(([]int(nil)), (s)...) }`, 1},
		{"source evaluated once", `func f(get func() []int) []int { return append([]int(nil), get()...) }`, 1},
		{"make copy", `func f(s []int) []int { d := make([]int, len(s)); copy(d, s); return d }`, 1},
		{"field source", `type S struct { s []int }; func f(s *S) []int { d := make([]int, len(s.s)); copy(d, s.s); return d }`, 1},
		{"case body", `func f(s []int) []int { switch { default: d := make([]int, len(s)); copy(d, s); return d } }`, 1},
		{"comm body", `func f(ch chan []int) { select { case s := <-ch: d := make([]int, len(s)); copy(d, s) } }`, 1},
		{"prefix", `func f(s []int) []int { return append([]int{1}, s...) }`, 0},
		{"append element", `func f(s int) []int { return append([]int{}, s) }`, 0},
		{"string append", `func f(s string) []byte { return append([]byte(nil), s...) }`, 0},
		{"string copy", `func f(s string) []byte { d := make([]byte, len(s)); copy(d, s); return d }`, 0},
		{"reuse", `func f(s, d []int) []int { return append(d[:0], s...) }`, 0},
		{"explicit capacity", `func f(s []int) []int { d := make([]int, len(s), len(s)+1); copy(d, s); return d }`, 0},
		{"append capacity", `func f(s []int) []int { return append(make([]int, 0, 100), s...) }`, 0},
		{"used count", `func f(s []int) int { d := make([]int, len(s)); return copy(d, s) }`, 0},
		{"different source", `func f(s, other []int) []int { d := make([]int, len(s)); copy(d, other); return d }`, 0},
		{"different field", `type S struct { a, b []int }; func f(s S) []int { d := make([]int, len(s.a)); copy(d, s.b); return d }`, 0},
		{"different receiver", `type S struct { a []int }; func f(s, other S) []int { d := make([]int, len(s.a)); copy(d, other.a); return d }`, 0},
		{"effectful source", `func f(get func() []int) []int { d := make([]int, len(get())); copy(d, get()); return d }`, 0},
		{"intervening statement", `func f(s []int) []int { d := make([]int, len(s)); s[0]++; copy(d, s); return d }`, 0},
		{"reassignment", `func f(s []int) []int { s = make([]int, len(s)); copy(s, s); return s }`, 0},
		{"shadowed source", `func f(s []int) []int { { s := make([]int, len(s)); copy(s, s); return s } }`, 0},
		{"shadowed append", `func f(s []int, append func([]int, ...int) []int) []int { return append([]int(nil), s...) }`, 0},
		{"shadowed copy", `func f(s []int, copy func([]int, []int)) []int { d := make([]int, len(s)); copy(d, s); return d }`, 0},
		{"shadowed len", `func f(s []int, len func([]int) int) []int { d := make([]int, len(s)); copy(d, s); return d }`, 0},
		{"shadowed make", `func f(s []int, make func(int, int) []int) []int { d := make(0, len(s)); copy(d, s); return d }`, 0},
		{"shadowed nil", `func f(s []int, nil []int) []int { return append([]int(nil), s...) }`, 0},
		{"array", `func f(s [2]int) [2]int { d := [2]int{}; copy(d[:], s[:]); return d }`, 0},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			offenses := runExtractedTypedCop(t, newSlicesCloneFile(), "package p\n"+tc.src)
			require.Len(t, offenses, tc.want)
			for _, offense := range offenses {
				assert.Equal(t, "Lint/SlicesClone", offense.CopName)
				assert.Contains(t, offense.Message, "slices.Clone")
				assert.Equal(t, 2, offense.Pos.Line)
			}
		})
	}
}

func TestSlicesCloneRunner(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	require.NoError(t, os.WriteFile("go.mod", []byte("module example.test\n\ngo 1.26\n"), 0o600))
	const src = "package p\nfunc f(s []int) []int { return append([]int(nil), s...) }\n"
	for name, content := range map[string]string{
		"legacy/sample.go":            src,
		"production/sample.go":        src,
		"tests/sample_test.go":        src,
		"external/sample_test.go":     "package p_test\nfunc f(s []int) []int { return append([]int{}, s...) }\n",
		"pkg/config/latest/sample.go": src,
		"pkg/config/v0/sample.go":     src,
		"pkg/config/v15/sample.go":    src,
		"generated/sample.go":         "// Code generated by fixture; DO NOT EDIT.\n" + src,
		"suppressed/sample.go":        "//rubocop:disable-file Lint/SlicesClone\n" + src,
		"inline/sample.go":            "package p\nfunc f(s []int) []int { return append([]int(nil), s...) } //rubocop:disable Lint/SlicesClone\n",
	} {
		require.NoError(t, os.MkdirAll(filepath.Dir(name), 0o700))
		require.NoError(t, os.WriteFile(name, []byte(content), 0o600))
	}
	var output bytes.Buffer
	r := runner.New(nil, config.DefaultConfig(), &output).WithProgramCops([]prog.Cop{NewLintSlicesClone(cop.WithScope(cop.Not(cop.UnderDir("legacy"))))})
	count, err := r.Run([]string{"."})
	require.NoError(t, err)
	assert.Equal(t, 6, count, output.String())
}

func TestSlicesCloneRetainsHealthyPackagesWithBrokenTests(t *testing.T) {
	t.Parallel()
	files := coptest.ProgramFiles{
		"go.mod":           "module example.test\n\ngo 1.26\n",
		"good/p.go":        slicesCloneFixture,
		"good/p_test.go":   "package p\nvar _ = missing\n",
		"legacy/p_test.go": "package legacy\nvar _ = missing\n",
		"tests/p_test.go":  slicesCloneFixture,
	}
	c := NewLintSlicesClone(cop.WithScope(cop.Not(cop.UnderDir("legacy"))))
	offenses := coptest.RunProgram(t, c, files)
	require.Len(t, offenses, 2)
	var got []string
	for _, offense := range offenses {
		assert.Equal(t, "Lint/SlicesClone", offense.CopName)
		got = append(got, filepath.Base(filepath.Dir(offense.Pos.Filename)))
	}
	assert.ElementsMatch(t, []string{"good", "tests"}, got)
}
